### ISSUE TITLE
model focus: delete listener

### ISSUE THREAD

**Issue by jpasski** [CoastalHacking/semiotics-main#39]
A previously selected element isn't removed from focus if it's deleted. It'll be a stale reference which will cause ChangeCommands to fail like so:

``` java
!ENTRY org.eclipse.emf.common 2 0 2016-08-10 07:47:18.552
!MESSAGE An exception was ignored during command execution
!STACK 0
org.eclipse.emf.common.util.WrappedException: An exception was ignored during command execution
    at org.eclipse.emf.common.command.BasicCommandStack.handleError(BasicCommandStack.java:281)
    at org.eclipse.emf.transaction.impl.AbstractTransactionalCommandStack.handleError(AbstractTransactionalCommandStack.java:125)
    at org.eclipse.emf.transaction.impl.AbstractTransactionalCommandStack.execute(AbstractTransactionalCommandStack.java:229)
    at org.eclipse.emf.emfstore.internal.client.transaction.EMFStoreTransactionalCommandStack.execute(EMFStoreTransactionalCommandStack.java:52)
    at io.opensemantics.semiotics.extension.provider.AdapterEventHandler.handleEvent(AdapterEventHandler.java:146)
    at org.eclipse.equinox.internal.event.EventHandlerWrapper.handleEvent(EventHandlerWrapper.java:201)
    at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:197)
    at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:1)
    at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
    at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
Caused by: org.eclipse.emf.transaction.RollbackException: 
    at org.eclipse.emf.transaction.impl.TransactionImpl.commit(TransactionImpl.java:405)
    at org.eclipse.emf.transaction.impl.TransactionalCommandStackImpl.doExecute(TransactionalCommandStackImpl.java:70)
    at org.eclipse.emf.transaction.impl.AbstractTransactionalCommandStack.execute(AbstractTransactionalCommandStack.java:165)
    at org.eclipse.emf.transaction.impl.AbstractTransactionalCommandStack.execute(AbstractTransactionalCommandStack.java:219)
    ... 7 more
```

**Comment by jpasski** [comment]
[Successful build](https://travis-ci.org/CoastalHacking/semiotics-main/builds/152743553), closing.
